// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useEffect, useState } from "react";
import { color, courseDetails } from "../../../utils";

function Category() {
 let count=0
  return (
    <section className="section category" aria-label="category">
      
        <div className="sub-container">
           <p className="section-subtitle">Popular Courses</p>

        <h2 className="h2 section-title">
          Pick A <span className="span">Course</span> To Get Started.
        </h2>

        <p className="section-text">
          Interactive lessons designed for anytime, anywhere learning.
        </p>
        </div>
       

        <ul className="grid-list">
          {courseDetails.map((_,i)=>{
            if(_.isTopCourse)
            {
              count=count+1
              return  <>
            <li>
            <div
              className="category-card"
              style={{ "--color": color[count-1]}}
            >
              <div className="card-icon">
                <img
                  src={_.thumbnail?_.thumbnail:"/assets/images/category-1.svg"}
                  width="40"
                  height="40"
                  loading="lazy"
                  alt="Online Degree Programs"
                  className="img"
                />
              </div>
              <h3 className="h3">
                <a href="#" className="card-title">
                  {_.title}
                </a>
              </h3>
              <p className="card-text">
                 {_.description.split(0,10)+".."}
              </p>
              <span className="card-badge">Know More</span>
            </div>
          </li>
            </>
            
            }
            else{
                  return null
            }
          })}
        </ul>
       
    </section>
  );
}

export default Category;
