// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useEffect, useState } from "react";

function Category() {
 let count=0
  let courseDetails= [
          {
            "id": "NVR",
            "name": "11 Plus",
            "title": "NVR",
            "image": "https://campus.w3schools.com/cdn/shop/files/react_930c122c-8d12-4a0a-85ef-67ca7e78bccf_1200x1200.png?v=1734688338",
            "description": "Learn the fundamentals of web development using HTML and CSS.",
            "content": [
                {"id": "Module - 01: Shapes",
                 "description": "Shows the shape"
                },
                {"id": "Module - 02: Counting",
                 "description": "Shows the shape"
                },
                {"id": "Module - 01: Pointing",
                 "description": "Shows the shape"
                },
                {"id": "Module - 01: Shading and Line Types",
                 "description": "Shows the shape"
                },
                {"id": "Module - 01: Order and Position",
                 "description": "Shows the shape"
                }
            ],
              isTopCourse:true
          },
          {
            "id": "VR",
            "name": "11 Plus",
            "title": "VR",
            "image": "https://campus.w3schools.com/cdn/shop/files/react_930c122c-8d12-4a0a-85ef-67ca7e78bccf_1200x1200.png?v=1734688338",
            "description": "A deep dive into JavaScript basics and DOM manipulation.",
            "content": [
                {"id": "Module - 01: Shapes",
                 "description": "Shows the shape"
                },
                {"id": "Module - 02: Counting",
                 "description": "Shows the shape"
                },
                {"id": "Module - 03: Pointing",
                 "description": "Shows the shape"
                },
                {"id": "Module - 04: Shading and Line Types",
                 "description": "Shows the shape"
                }
            ],
            isTopCourse:true
          },
          {
            "id": "Math",
            "name": "11 Plus",
            "title": "Maths",
            "image": "path_to_image_1.jpg",
            "description": "Learn the fundamentals of web development using HTML and CSS.",
            "content": [
                {"id": "Module - 01: Shapes",
                 "description": "Shows the shape"
                },
                {"id": "Module - 02: Counting",
                 "description": "Shows the shape"
                }
            ]
          },
          {
            "id": "English",
            "name": "11 Plus",
            "title": "English",
            "image": "path_to_image_1.jpg",
            "description": "Learn the fundamentals of web development using HTML and CSS.",
            "content": [
                {"id": "Module - 01: Shapes",
                 "description": "Shows the shape"
                },
                {"id": "Module - 02: Counting",
                 "description": "Shows the shape"
                },
                {"id": "Module - 03: Pointing",
                 "description": "Shows the shape"
                },
                {"id": "Module - 04: Shading and Line Types",
                 "description": "Shows the shape"
                },
                {"id": "Module - 05: Order and Position",
                 "description": "Shows the shape"
                },
                {"id": "Module - 06: Order and Position",
                 "description": "Shows the shape"
                }
            ],
              isTopCourse:true
          },  
          {
            "id": "ds101",
            "name": "IQ and Critical Thinking",
            "title": "Introduction to Python",
            "image": "path_to_image_3.jpg",
            "description": "Start your Python journey with this beginner-friendly course."
          },
          {
            "id": "ds102",
            "name": "IQ and Critical Thinking",
            "title": "Machine Learning Basics",
            "image": "path_to_image_4.jpg",
            "description": "Learn the fundamentals of machine learning algorithms.",
              isTopCourse:true
          }
        ]
  let color=["170, 75%, 41%","351, 83%, 61%","229, 75%, 58%","42, 94%, 55%"]
 
  return (
    <section className="section category" aria-label="category">
      <div className="container">
        <p className="section-subtitle">Categories</p>

        <h2 className="h2 section-title">
          Online <span className="span">Classes</span> For Remote Learning.
        </h2>

        <p className="section-text">
          Interactive lessons designed for anytime, anywhere learning.
        </p>

        <ul className="grid-list">
          {courseDetails.map((_,i)=>{
            if(_.isTopCourse)
            {
              count=count+1
              return  <>
            <li>
            <div
              className="category-card"
              style={{ "--color": color[count-1]}}
            >
              <div className="card-icon">
                <img
                  src="/assets/images/category-1.svg"
                  width="40"
                  height="40"
                  loading="lazy"
                  alt="Online Degree Programs"
                  className="img"
                />
              </div>
              <h3 className="h3">
                <a href="#" className="card-title">
                  {_.title}
                </a>
              </h3>
              <p className="card-text">
                 {_.description.split(0,10)+".."}
              </p>
              <span className="card-badge">Know More</span>
            </div>
          </li>
            </>
            
            }
            else{
                  return null
            }
          })}
          {/* <li>
            <div
              className="category-card"
              style={{ "--color": "170, 75%, 41%" }}
            >
              <div className="card-icon">
                <img
                  src="/assets/images/category-1.svg"
                  width="40"
                  height="40"
                  loading="lazy"
                  alt="Online Degree Programs"
                  className="img"
                />
              </div>
              <h3 className="h3">
                <a href="#" className="card-title">
                  Online Degree Programs
                </a>
              </h3>
              <p className="card-text">
                Lorem ipsum dolor consec tur elit adicing sed umod tempor.
              </p>
              <span className="card-badge">7 Courses</span>
            </div>
          </li>

          <li>
            <div
              className="category-card"
              style={{ "--color": "351, 83%, 61%" }}
            >
              <div className="card-icon">
                <img
                  src="/assets/images/category-2.svg"
                  width="40"
                  height="40"
                  loading="lazy"
                  alt="Non-Degree Programs"
                  className="img"
                />
              </div>
              <h3 className="h3">
                <a href="#" className="card-title">
                  Non-Degree Programs
                </a>
              </h3>
              <p className="card-text">
                Lorem ipsum dolor consec tur elit adicing sed umod tempor.
              </p>
              <span className="card-badge">4 Courses</span>
            </div>
          </li>

          <li>
            <div
              className="category-card"
              style={{ "--color": "229, 75%, 58%" }}
            >
              <div className="card-icon">
                <img
                  src="/assets/images/category-3.svg"
                  width="40"
                  height="40"
                  loading="lazy"
                  alt="Off-Campus Programs"
                  className="img"
                />
              </div>
              <h3 className="h3">
                <a href="#" className="card-title">
                  Off-Campus Programs
                </a>
              </h3>
              <p className="card-text">
                Lorem ipsum dolor consec tur elit adicing sed umod tempor.
              </p>
              <span className="card-badge">8 Courses</span>
            </div>
          </li>

          <li>
            <div
              className="category-card"
              style={{ "--color": "42, 94%, 55%" }}
            >
              <div className="card-icon">
                <img
                  src="/assets/images/category-4.svg"
                  width="40"
                  height="40"
                  loading="lazy"
                  alt="Hybrid Distance Programs"
                  className="img"
                />
              </div>
              <h3 className="h3">
                <a href="#" className="card-title">
                  Hybrid Distance Programs
                </a>
              </h3>
              <p className="card-text">
                Lorem ipsum dolor consec tur elit adicing sed umod tempor.
              </p>
              <span className="card-badge">8 Courses</span>
            </div>
          </li> */}
        </ul>
      </div>
    </section>
  );
}

export default Category;
